title: Hao Yang Lin - Data Science Portfolio
description: Graduate Student | Data Science & Machine Learning
url: "https://hylin0517.github.io"
baseurl: ""

# Use a simple theme
theme: cayman

# Exclude README from the site
exclude:
  - README.md
