title: Hao Yang Lin - Data Science Portfolio
description: MSA Student @ GT | Data Science & Machine Learning
url: "https://hylin0517.github.io"
baseurl: ""

# Use a simple theme
theme: jekyll-theme-cayman

# Exclude README from the site
exclude:
  - README.md
